version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      # 集群名称 elasticsearch
      - "cluster.name=elasticsearch"
      # 以单一节点模式启动
      - "discovery.type=single-node"
      # 设置使用jvm内存大小
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
  kibana:
    image: kibana:6.4.0
    container_name: kibana
    links:
      # 可以用es这个域名访问elasticsearch服务
      - elasticsearch:es
    depends_on:
      # kibana在elasticsearch启动之后再启动
      - elasticsearch
    environment:
      # 设置访问elasticsearch的地址
      - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601
  logstash:
    image: logstash:6.4.0
    container_name: logstash
    volumes:
      # 挂载logstash的配置文件
      - ./logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      # kibana在elasticsearch启动之后再启动
      - elasticsearch
    links:
      # 可以用es这个域名访问elasticsearch服务
      - elasticsearch:es
    ports:
      - 4560:4560