spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: consumer_group
      enable-auto-commit: true
      auto-offset-reset: latest