server:
  port: 8081
spring:
  application:
    name: member-server
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      client-id: tallon
      client-secret: tallon
      access-token-uri: http://localhost:9090/oauth/token
      user-authorization-uri: http://localhost:9090/oauth/authorize
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
    authorization:
      check-token-access: http://localhost:9090/oauth/check_token