version: '3.1'
services:
  zk:
    image: wurstmeister/zookeeper
    container_name: zk
    ports:
      - 2181:2181
    volumes:
      - ./localtime:/etc/localtime wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./localtime:/etc/localtime wurstmeister/kafka